### ISSUE TITLE
Recreation of tasks does not work

### ISSUE THREAD

**Issue by ghost** [Kirska/Habitica_ToDoOvers#29]
Hey there, 

I really love this project, so I have a really high amount of To Do Overs. 
Worked fine for months, but all of a sudden it does not recreate the To do's. 
I have two accounts, it doesn't work on either.

Maybe you could look into it. I would highly appreciate it!

**Comment by TheRealWebGremlin** [comment]
I'm having the same issue. Worked fine ever since I started using it ~6 months ago, but now it has stopped working seemingly out of the blue. The first time I noticed it was last Monday (12/12/22). I had completed a task that should be re-created without delay. It is now Wednesday and the task has yet to re-appear on Habitica. It is still set up in my ToDoOver database.

Your tool has been an amazing help to me. If you could help us resolve this issue I would be very grateful.

**Comment by Kirska** [comment]
The task to recreate tasks expired about a week ago. That's my bad for forgetting to renew it. I've had two surgeries this year and haven't been the best about renewing it. Lemme know if it's still not working.

**Comment by TheRealWebGremlin** [comment]
That was fast. It's working on my end again. Thank you very much for your quick help, @Kirska! Do you have a way to accept donations? I'll gladly buy you a cup of coffee :)

**Comment by Kirska** [comment]
That is not necessary! But here is my buy me a coffee https://www.buymeacoffee.com/kirska
I hope to get more work on this done and migrate it to AWS but I have so many projects at work and in volunteering right now.
